# Site settings
title: 'Altairs Portfolio & Blog'
description: 'The portfolio website of K. Celinski a.k.a Altair115'
keywords: 'Blog, Development, Portfolio'
url: 'https://altair115.github.io' # your host

# nav ：&emsp;
nav: # The best experience is six labels, and each label should not exceed 4 Chinese characters
  Home: '/'
  Tags: '/tags.html'
  Timeline: '/timeline.html'
  About: '/about.html'
  Contact: '/friendLink.html'

# Blogger/Author of blog
author: true
name: 'K. Celinski'
NickName: 'Altair115'
webtitle: 'your awesome webtitle'
bio: 'your awesome bio'
about: true
aboutyou: 'your introduction'
portraits: '/assets/P4 Yu.jpg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:kevin.celinski@outlook.com'
  weixin: '' # Address where your WeChat QR code is stored
  qq: '' # Your qq QR code storage address or http://wpa.qq.com/msgrd?v=3&uin='your QQ number '& site = qq & menu = yes
  github: ''
  Codepen: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  juejin: ''
  twitch: ''

# Pagination
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# Code highlighting: rouge
highlighter: rouge
# Code highlighting theme using pygments theme: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango Choose any theme name you like and fill it in single quotes below
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://jekyllrb.com'

# Comment Best experience Choose between disqus, livere and Gitment
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github Username
Gitment_repo: ''  # github Repo Location
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['linkedin']

# Baidu Statistics Fill in your own url code in baidu-url
baidu: false
baidu-url: ''
# Google Analytics Fill in your tracking ID obtained in Google Analytics in google-ID
google: false
google-ID: ''

# Alternative color of blog header information (this part is not used as a site variable in the site, it is written in the post header information to be used as a page variable)
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
